import type { PlanRow } from '../pages/ai-hub-v3/PlansAndApprovalsTab';
import type { Reversibility } from '../types/reversibility';
import { formatReversibilityLabel } from '../types/reversibility';
import { formatTokenBurn } from '../types/tokenBurn';
import { getPlanTokenBurn } from '../pages/ai-hub-v3/plansMvpConstants';

export type RemediationOptionDownload = {
  id: string;
  title: string;
  description: string;
  rawCommands: string;
  reversible?: Reversibility;
};

export function buildRemediationPlanMarkdown(
  plan: PlanRow,
  option: RemediationOptionDownload,
  rootCause?: { aggregatedFinding?: string; rootCauseNarrative?: string },
): string {
  const burn = getPlanTokenBurn(plan.id);

  const lines = [
    `# Remediation plan: ${plan.name ?? plan.id}`,
    '',
    `**Summary:** ${plan.synopsis}`,
    `**Trigger domain:** ${plan.triggerDomain}`,
    `**Status:** ${plan.status}`,
    '',
    '## Root cause',
    '',
    rootCause?.aggregatedFinding ?? '—',
    '',
    rootCause?.rootCauseNarrative ?? '',
    '',
    '## Selected remediation option',
    '',
    `**${option.title}**`,
    '',
    option.description,
    '',
    `**Reversibility:** ${formatReversibilityLabel(option.reversible ?? 'Reversible')}`,
    `**Analysis token burn:** ${formatTokenBurn(burn.analysis)}`,
    '',
    '## Commands',
    '',
    '```bash',
    option.rawCommands,
    '```',
    '',
    '---',
    '_Generated by Agentic OpenShift — review all commands before manual execution._',
  ];

  return lines.join('\n');
}

export function downloadRemediationPlanMarkdown(
  plan: PlanRow,
  option: RemediationOptionDownload,
  rootCause?: { aggregatedFinding?: string; rootCauseNarrative?: string },
): void {
  const markdown = buildRemediationPlanMarkdown(plan, option, rootCause);
  const slug = (plan.name ?? plan.id).replace(/[^a-z0-9-]+/gi, '-').toLowerCase();
  const filename = `${slug}-remediation-plan.md`;
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function buildAnalysisReportMarkdown(
  plan: PlanRow,
  rootCause: { aggregatedFinding: string; rootCauseNarrative: string },
): string {
  const burn = getPlanTokenBurn(plan.id);
  const lines = [
    `# Analysis report: ${plan.name ?? plan.id}`,
    '',
    `**Summary:** ${plan.synopsis}`,
    `**Trigger domain:** ${plan.triggerDomain}`,
    '',
    '## Findings',
    '',
    rootCause.aggregatedFinding,
    '',
    rootCause.rootCauseNarrative,
    '',
    `**Analysis token burn:** ${burn.analysis} tokens`,
    '',
    '---',
    '_Investigation-only proposal — no remediation options were generated._',
  ];
  return lines.join('\n');
}

export function downloadAnalysisReportMarkdown(
  plan: PlanRow,
  rootCause: { aggregatedFinding: string; rootCauseNarrative: string },
): void {
  const markdown = buildAnalysisReportMarkdown(plan, rootCause);
  const slug = (plan.name ?? plan.id).replace(/[^a-z0-9-]+/gi, '-').toLowerCase();
  const filename = `${slug}-analysis-report.md`;
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}
